import "@mantine/core/styles.css";
import { Inter } from "next/font/google";
import "./globals.css";
import { MantineProvider } from "@mantine/core";
import { theme } from "../../theme";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='conatiner'>
          <div className='wrapper'>
            <MantineProvider theme={theme}>{children}</MantineProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
